#!/usr/bin/env python3
"""Embed the photographic damage decals into the Clone Wars panel pages.

Reads  assets/damage-decals/  (manifest.json + PNGs on flat #808080),
processes each sprite:
  * background keyed to alpha (distance from mid-grey, soft knee, blurred)
  * over-saturated sprite blues muted toward the hull palette
  * downscaled to 512 px, encoded as WebP-with-alpha data URIs
and splices a  <script id="cw-decals">  block into BOTH panel pages
(mockup/index.html and plugin/Source/ui/ui.html), before the main script
so the patina engine can see it. Re-runnable whenever the sprite set
changes — splice, don't retype.
"""

import base64, colorsys, io, json, os, re, sys

from PIL import Image, ImageFilter
import numpy as np

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
DECALS = os.path.join(ROOT, "assets", "damage-decals")
PAGES = [
    os.path.join(ROOT, "vst3-apps", "clone-wars", "mockup", "index.html"),
    os.path.join(ROOT, "vst3-apps", "clone-wars", "plugin", "Source", "ui", "ui.html"),
]
OUT_SIZE = 512
QUALITY = 78


def process(path: str) -> bytes:
    im = Image.open(path).convert("RGB")
    a = np.asarray(im).astype(np.float32)

    # --- alpha: distance from flat mid-grey, soft knee ---------------------
    d = np.abs(a - 128.0).max(axis=2)
    alpha = np.clip((d - 5.0) / 22.0, 0.0, 1.0)
    alpha_im = Image.fromarray((alpha * 255).astype(np.uint8), "L")
    alpha_im = alpha_im.filter(ImageFilter.GaussianBlur(1.2))

    # --- mute the vivid sprite blues toward the hull's desaturated cobalt --
    r, g, b = a[..., 0] / 255, a[..., 1] / 255, a[..., 2] / 255
    mx = np.maximum(np.maximum(r, g), b)
    mn = np.minimum(np.minimum(r, g), b)
    sat = np.where(mx > 0, (mx - mn) / np.maximum(mx, 1e-6), 0)
    # hue for blue-dominant pixels only (cheap: blue channel dominant)
    blueness = np.clip((b - np.maximum(r, g)) / 0.25, 0, 1) * np.clip((sat - 0.25) / 0.3, 0, 1)
    # desaturate & darken proportionally to blueness
    grey = (r + g + b) / 3
    f = (blueness * 0.45)[..., None]
    rgb = np.stack([r, g, b], axis=2)
    rgb = rgb * (1 - f) + np.stack([grey, grey, grey], axis=2) * f
    rgb *= 1 - (blueness * 0.18)[..., None]
    out = Image.fromarray((np.clip(rgb, 0, 1) * 255).astype(np.uint8), "RGB")

    out = out.resize((OUT_SIZE, OUT_SIZE), Image.LANCZOS)
    alpha_im = alpha_im.resize((OUT_SIZE, OUT_SIZE), Image.LANCZOS)
    out.putalpha(alpha_im)

    buf = io.BytesIO()
    out.save(buf, "WEBP", quality=QUALITY)
    return buf.getvalue()


def main() -> int:
    manifest = json.load(open(os.path.join(DECALS, "manifest.json")))
    entries = []
    total = 0
    for item in manifest["files"]:
        data = process(os.path.join(DECALS, item["file"]))
        total += len(data)
        entries.append({
            "c": item["category"],
            "n": item["name"],
            "src": "data:image/webp;base64," + base64.b64encode(data).decode(),
        })
        print(f"  {item['file']:36s} {len(data)/1024:6.1f} KB  {item['category']}")
    print(f"total embedded: {total/1024:.0f} KB for {len(entries)} sprites")

    block = ('<script id="cw-decals">\n'
             "/* photographic damage decals — generated by tools/embed-decals.py */\n"
             "window.CW_DECALS = " + json.dumps(entries) + ";\n"
             "</script>\n")

    for page in PAGES:
        s = open(page).read()
        s = re.sub(r'<script id="cw-decals">.*?</script>\n', "", s, flags=re.S)
        i = s.find("<script>\n\"use strict\";")
        assert i >= 0, page
        s = s[:i] + block + s[i:]
        open(page, "w").write(s)
        print(f"spliced into {os.path.relpath(page, ROOT)} ({len(s)/1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
