/*  LEVEL CALIBRATION — measured, not modelled.

    Renders every habit, reads the peak the output stage was handed BEFORE it
    acted, and computes the trim that puts that peak on the target. The trim is
    applied at the output multiply, after every nonlinearity in the instrument,
    so the pre-limiter peak scales exactly with it and a single pass is exact —
    which the verification run at the end checks rather than assumes.

    It only ever REDUCES. A quiet specimen is quiet because that is what it is,
    and making everything the same loudness would flatten the catalogue.

        cmake --build test/build --config Release --target ab67gaincal
        ab67gaincal            prints the table
        ab67gaincal --verify   reports what the current table achieves
*/
#include "../Source/Engine.h"
#include "../Source/Lattice.h"
#include <cstdio>
#include <cstring>
#include <cmath>
#include <vector>
#include <algorithm>

static const int SR = 48000, BLK = 512, NB = 190;   // 2.0 s, past the strike

/*  The target. The compressor's threshold is 0.55 of the ceiling and the
    ceiling at rest is 0.935, so the knee is at 0.514. Landing the peak of a
    held note just under that leaves the compressor for real transients and the
    brickwall for accidents, which is what they are for. */
static const double TARGET = 0.50;

struct M { double pre, post, minGr; int blocksLimited; };

static M render (int habit, int note)
{
    ax::Engine e; e.prepare ((double) SR, BLK);
    ax::applyHabit (habit, e.p);
    e.p.sustain = 0.8f;
    e.service();
    e.preLimitPeak.store (0.0f);
    e.noteOn (note, 0.95f);
    std::vector<float> L (BLK), R (BLK);
    M m; m.post = 0; m.minGr = 1; m.blocksLimited = 0;
    for (int b = 0; b < NB; ++b)
    {
        e.service();
        e.process (L.data(), R.data(), BLK);
        for (int i = 0; i < BLK; ++i) m.post = std::max (m.post, (double) std::abs (L[(size_t) i]));
        const double g = e.limitGR.load();
        m.minGr = std::min (m.minGr, g);
        if (g < 0.98) ++m.blocksLimited;
    }
    m.pre = e.preLimitPeak.load();
    return m;
}

/*  A specimen is played across its range, not at one note: habit 240's gain
    reduction ran from 0.56 at one note to 0.13 at another, so calibrating on a
    single note would leave the rest of the keyboard in the limiter. */
static double worstPre (int habit)
{
    double w = 0;
    for (int n : { 40, 46, 52, 58, 64 }) w = std::max (w, render (habit, n).pre);
    return w;
}

int main (int argc, char** argv)
{
    const bool verify = (argc > 1 && std::strcmp (argv[1], "--verify") == 0);

    if (! verify)
    {
        std::printf ("// generated by test/gaincal.cpp -- do not hand-edit\n");
        for (int h = 0; h < 256; ++h)
        {
            const double pre = worstPre (h);
            /*  The measurement is taken through whatever trim is already
                compiled in, so fold it back out. That makes the generator
                idempotent: run it on a calibrated build and it reproduces the
                same table instead of trimming the trim. */
            double trim = (pre > 1e-9) ? (double) ab::habitTrim (h) * TARGET / pre : 1.0;
            if (trim > 1.0) trim = 1.0;                 // only ever reduce
            if (trim < 0.0004) trim = 0.0004;   // one specimen genuinely screams
            std::printf ("%.6ff,%s", trim, (h % 8 == 7) ? "\n" : " ");
        }
        return 0;
    }

    std::printf ("verifying the table that is compiled in\n\n");
    int inLimiter = 0, hot = 0;
    double worstBlocks = 0, quietest = 1e9, loudest = 0;
    std::vector<double> pks;
    for (int h = 0; h < 256; ++h)
    {
        double blocks = 0, pre = 0, mg = 1;
        for (int n : { 40, 52, 64 })
        { const M m = render (h, n);
          blocks = std::max (blocks, (double) m.blocksLimited);
          pre = std::max (pre, m.pre); mg = std::min (mg, m.minGr); }
        pks.push_back (pre);
        quietest = std::min (quietest, pre); loudest = std::max (loudest, pre);
        worstBlocks = std::max (worstBlocks, blocks);
        if (blocks > NB * 0.5)
        {
            ++inLimiter;
            std::printf ("    habit %3d is still in the limiter: pre-limiter peak %.3f,"
                         " trim %.6f, %.0f blocks\n", h, pre, ab::habitTrim (h), blocks);
        }
        if (pre > TARGET * 1.35) ++hot;
    }
    std::sort (pks.begin(), pks.end());
    std::printf ("  habits spending over half a note in the limiter : %d of 256\n", inLimiter);
    std::printf ("  habits above the target by more than 35 %%       : %d of 256\n", hot);
    std::printf ("  worst blocks limited in one note                : %.0f of %d\n", worstBlocks, NB);
    std::printf ("  pre-limiter peak  min %.4f  median %.4f  max %.4f\n",
                 quietest, pks[pks.size()/2], loudest);
    std::printf ("  spread quietest..loudest                        : %.1f dB\n",
                 20.0 * std::log10 (loudest / std::max (1e-9, quietest)));
    return 0;
}
