"use strict";
const fs = require("fs");
const P = "c:/Users/peter/Dropbox/ACTIVITIES/00 VSCODE/BrokildApps/BWFX-BUGLIST.md";
let s = fs.readFileSync(P, "utf8");
const NL = s.indexOf(String.fromCharCode(13, 10)) >= 0 ? String.fromCharCode(13, 10) : String.fromCharCode(10);
const D = String.fromCharCode(8212);
const BT = String.fromCharCode(96);

const L = [
"",
"### 17. Tempo changes wreck the synced effects " + D + " SPEC, awaiting go",
"",
"Peter 2026-08-30: \"when changing DAW tempo, a lot of the synced effects do",
"not follow. If i start at 120 bpm all sound good when adding echoes,",
"kieranator, stutters " + D + " but changing tempo in daw just creates a mess.\"",
"",
"Reproduced offline (" + BT + "test/tempoprobe.cpp" + BT + ", a fake host whose ppq advances at",
"the current tempo, exactly as JUCE's playhead does). There are **four**",
"separate faults, and the loudest one is not the one the wording suggests.",
"",
"#### 17a. ECHO splices on EVERY tempo change (the audible one)",
"",
"The timing is not the problem: measured across 120->90, 120->150 and 120->121",
"the echo lands on the new grid immediately and exactly (0.6667 / 0.4000 /",
"0.4959 s against a 1/4 note). What is wrong is the transition.",
"",
"| change | worst sample step, settled | around the change |",
"|---|---|---|",
"| 120 -> 90 | 0.0229 | **1.4674** (64x) |",
"| 120 -> 150 | 0.0229 | **1.5195** (66x) |",
"| 120 -> 121 | 0.0229 | **0.1638** (7x) |",
"",
"Even a one-BPM nudge is an audible tick. Cause, in " + BT + "bwfx_modules.cpp:248-263" + BT + ":",
"the snap test is " + BT + "abs(ms - lastSyncMs) > lastSyncMs * 0.5f" + BT + " " + D + " a 50 % change in",
"delay TIME. Since time is inversely proportional to tempo, that only fires",
"below old/1.5 or above 2x, so every ordinary tempo move falls under it and",
"GLIDES instead. And the glide is not smooth: the time is evaluated once per",
"32-sample sub-block and held constant across it, so each sub-block teleports",
"the read pointer by ~115 samples inside a 32-sample window " + D + " a hard splice",
"every sub-block for the whole glide, fed back through the feedback path.",
"Snapping (the other branch) splices once instead. Both are wrong.",
"",
"**Fix:** a crossfaded tap. When the synced time changes, fade the old read",
"position out and the new one in over ~20-30 ms instead of moving one pointer.",
"Clickless AND on the new grid at once, so the Black Rider lesson (\"gliding in",
"lands the first echo early\") is honoured without the splice.",
"",
"#### 17b. Nothing but the KIERANATOR knows where the BAR is",
"",
"This is the one that matches \"do not follow\". Grepping the module file:",
BT + BT + BT,
"1235:    void setClock (double ppq, bool playing) override { ... }   // KIERANATOR",
BT + BT + BT,
"That is the ONLY override in the whole rack. ECHO, GATE and HARMONIC receive",
"a BPM and nothing else, so they match the tempo's PERIOD but their PHASE is",
"wherever it happened to land " + D + " they are free-running LFOs whose rate is",
"tempo-derived, not bar-locked oscillators. That is exactly why it \"sounds",
"good at 120\": you set it up by ear at one tempo, and after any change the",
"phase relationship to the bar is arbitrary. The bench never noticed because",
"it only ever measures the gate PERIOD, never its phase against the bar",
"(" + BT + "bench.cpp:477-479" + BT + ").",
"",
"**Fix:** the rate-based modules already receive " + BT + "setClock" + BT + "; they should use it,",
"deriving phase from ppq when a host clock exists and free-running only when",
"it does not.",
"",
"#### 17c. Seven of nine hosts never send the bar at all",
"",
"Only Full Metal Racket and Artefact B2311.22 call " + BT + "bwfxRack.setTransport" + BT + ".",
"Photo-Synth 2, Escape Room, Blade Ruiner, Black Rider, Hairfryer and Clone",
"Wars call " + BT + "setBpm" + BT + " only, so " + BT + "ppqIn" + BT + " stays at its init -1 and the KIERANATOR",
"takes its free-run branch permanently " + D + " it is never bar-locked in any of",
"them. And the two hosts that DO call it pass " + BT + "ppq ? *ppq : 0.0" + BT + ", telling the",
"rack \"you are exactly at bar 0\" every block when the host has no position,",
"where the contract says <0 means unknown.",
"",
"#### 17d. Three smaller hazards found on the way",
"",
"* **A stale BPM is held forever.** Every host nests the call inside",
"  " + BT + "if (auto bpm = pos->getBpm())" + BT + ", so a block with no tempo simply does not",
"  call " + BT + "setBpm" + BT + " and the rack keeps the old value. There is no \"no clock any",
"  more\" path back to FREE.",
"* **An unguarded 0 BPM causes two discontinuities.** Five hosts pass the",
"  host's value with no range check; " + BT + "Rack::setBpm" + BT + " clamps out-of-range to 0,",
"  which drops the rack to FREE for that block, fires ECHO's hard snap to the",
"  KNOB value, then snaps back the next block. Some hosts do report 0 while",
"  relocating. Black Rider and FMR already guard (20..999); the rest should.",
"* **" + BT + "EchoDelay::reset()" + BT + " does not clear " + BT + "lastSyncMs" + BT + "** (only " + BT + "prepare()" + BT + " does),",
"  so a module toggled off across a tempo change returns with a stale value",
"  and glides from the old delay time.",
"",
"#### 17e. KIERANATOR: the grid is right, the voices are not",
"",
"Measured, the step grid does follow (0.125 s steps at 120 BPM, 0.167 at 90,",
"0.100 at 150 " + D + " all correct). But " + BT + "stepLen" + BT + "/" + BT + "repLen" + BT + " are recomputed every",
"sub-block while a firing voice's counters (" + BT + "Voice::t" + BT + ", " + BT + "Voice::start" + BT + ") are raw",
"sample counts captured at the step boundary. So mid-step: RETRIG's",
"" + BT + "pos = v.t % repLen" + BT + " jumps, TAPESTOP re-derives its whole closed-form ramp",
"against a new " + BT + "stepLen" + BT + ", SHUFFLE's " + BT + "shuffleBack" + BT + " was computed from the OLD",
"one and now disagrees, and PITCH's " + BT + "span" + BT + " changes under an " + BT + "fmod" + BT + ". Slowing",
"down can also reach further back than the 10 s capture ring and read stale",
"audio. A firing voice must keep the geometry it started with.",
"",
"#### Why this survived",
"",
"**No test in the repo ever changes tempo mid-render.** Every sync test sets a",
"BPM once and renders (" + BT + "bench.cpp" + BT + " :433, :458, :489, :650, :1509, :1522). The fix",
"must add tempo-change coverage: timing after the change, worst sample step",
"across it, and phase against the bar for every synced module.",
"",
"Probe kept at " + BT + "test/tempoprobe.cpp" + BT + " (target " + BT + "tempoprobe" + BT + ").",
""].join(NL);

fs.writeFileSync(P, s + L);
console.log("BWFX buglist item 17 written");
